using System;
using System.IO;
using System.Linq;
using System.Text;
using Project.Scripts.AI;
using Project.Scripts.AI.GraphEditor;
using UnityEditor;
using UnityEngine;

namespace Project.Editor.AI
{
    [InitializeOnLoad]
    internal static class AiNodeGraphCodeGenerator
    {
        private const string GeneratedPath =
            "Assets/Project/Editor/BehaviourTreeGraph/Generated/GeneratedAiNodes.g.cs";

        static AiNodeGraphCodeGenerator()
        {
            EditorApplication.delayCall += Generate;
        }

        [MenuItem("Tools/AI/Regenerate Behaviour Tree Nodes")]
        private static void Generate()
        {
            Type[] nodeTypes = TypeCache.GetTypesWithAttribute<AiNodeAttribute>()
                .Where(type =>
                    typeof(AiNode).IsAssignableFrom(type) &&
                    !type.IsAbstract &&
                    !type.ContainsGenericParameters)
                .OrderBy(type => type.FullName)
                .ToArray();

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("using System;");
            source.AppendLine();
            source.AppendLine("namespace Project.Editor.AI.Generated");
            source.AppendLine("{");

            foreach (Type nodeType in nodeTypes)
            {
                string className = GetGeneratedClassName(nodeType);
                string typeName = GetCSharpTypeName(nodeType);
                AiNodeAttribute attribute =
                    nodeType.GetCustomAttributes(
                            typeof(AiNodeAttribute),
                            false)
                        .Cast<AiNodeAttribute>()
                        .Single();
                string nodeName = string.IsNullOrWhiteSpace(attribute.Name)
                    ? ObjectNames.NicifyVariableName(nodeType.Name)
                    : attribute.Name.Trim();
                string group = string.IsNullOrWhiteSpace(attribute.Group)
                    ? "AI"
                    : attribute.Group.Trim();

                source.AppendLine("    [Serializable]");
                source.AppendLine(
                    $"    [global::Unity.GraphToolkit.Editor.Node({ToLiteral(group)}, null, {ToLiteral(nodeName)})]");
                source.AppendLine(
                    $"    internal sealed class {className} : global::Project.Editor.AI.AttributedAiNodeGraphNode");
                source.AppendLine("    {");
                source.AppendLine(
                    $"        internal override Type RuntimeNodeType => typeof({typeName});");
                source.AppendLine("    }");
                source.AppendLine();
            }

            source.AppendLine("}");
            string contents = source.ToString();

            string directory = Path.GetDirectoryName(GeneratedPath);
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            if (File.Exists(GeneratedPath) &&
                File.ReadAllText(GeneratedPath) == contents)
                return;

            File.WriteAllText(GeneratedPath, contents);
            AssetDatabase.ImportAsset(
                GeneratedPath,
                ImportAssetOptions.ForceUpdate);
            Debug.Log($"Generated {nodeTypes.Length} Behaviour Tree graph node(s).");
        }

        private static string GetGeneratedClassName(Type type)
        {
            string value = type.FullName ?? type.Name;
            var builder = new StringBuilder(value.Length + 16);
            foreach (char character in value)
                builder.Append(char.IsLetterOrDigit(character) ? character : '_');
            builder.Append("_GeneratedGraphNode");
            return builder.ToString();
        }

        private static string GetCSharpTypeName(Type type)
        {
            return $"global::{(type.FullName ?? type.Name).Replace('+', '.')}";
        }

        private static string ToLiteral(string value)
        {
            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }
    }
}
